version: '3.4'

x-ionic-base: &ionic-base
  user: ${USER_ID}
  build: ./docker
  volumes:
    - ./app:/src
  working_dir: /src

services:
  ionic:
    <<: *ionic-base
    ports:
      - "8101:8100"

  ionic-cli:
    <<: *ionic-base
